### ISSUE TITLE
Releases Missing

### ISSUE THREAD

**Issue by kc9ryt** [iganeshk/AdGuardHome#8]
Hello,
Where can i find the released versions? I am really struggling trying to compile your code.

**Comment by iganeshk** [comment]
Hey! I haven't updated the source for a long time due to changing process of how the clients are built. But I've updated the patch which should get you started on releasing your own build. Follow the instructions below

```
git clone https://github.com/AdguardTeam/AdGuardHome
cd AdGuardHome
wget https://raw.githubusercontent.com/iganeshk/AdGuardHome/dev-assets/dark-mustard-theme.patch
git apply dark-mustard-theme.patch
# flags: GOOS - windows, linux and darwin // GOARCH - amd64, arm64
make GOOS='linux' GOARCH='amd64' VERSION='v1.5.0' CHANNEL='release' ... build-release
```

**Comment by iganeshk** [comment]
I've made several revisions to my comment, make sure you follow the latest.

**Comment by kc9ryt** [comment]
Thanks for the help. I was able to get the patch to install. Question on the patch. i was trying to add some of the other css elements to the patch but when i do i can no longer compile adguardhome. Any idea what would cause this? Here is my modified file.
[dark-mustard-theme.patch.zip](https://github.com/iganeshk/AdGuardHome/files/5898720/dark-mustard-theme.patch.zip)
